### ISSUE TITLE
Do tutorial on NodeJS/PostgreSQL

### ISSUE THREAD

**Issue by matty22** [lacyjpr/media#16]

**Comment by matty22** [comment]
https://scotch.io/tutorials/getting-started-with-node-express-and-postgres-using-sequelize

**Comment by lacyjpr** [comment]
https://www.khanacademy.org/computing/computer-programming/sql

**Comment by matty22** [comment]
I've finished both the Udemy course and KA tutorial for this card. So when you finish up the Udemy course, this card can be marked complete.
